apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.mediacontrols'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
if (expoModulesCorePlugin.exists()) {
  apply from: expoModulesCorePlugin
  applyKotlinExpoModulesCorePlugin()
  useExpoPublishing()
}

android {
  namespace "expo.modules.mediacontrols"
  compileSdkVersion 34

  defaultConfig {
    minSdkVersion 23
    targetSdkVersion 34
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  lintOptions {
    abortOnError false
  }

  sourceSets {
    main {
      java {
        srcDirs += 'src/main/java'
      }
    }
  }
}

repositories {
  google()
  mavenCentral()
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
  implementation "androidx.media:media:1.6.0"
  implementation "androidx.core:core-ktx:1.12.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
}
